<?php

use Phinx\Migration\AbstractMigration;
use Phinx\Db\Adapter\MysqlAdapter;

class CreateUsersTable extends AbstractMigration
{
  public function up() {
    $this->table('users', ['engine' => "InnoDB"])
      ->addColumn('username', 'string', ['null' => false, 'limit' => 255])
      ->addColumn('password', 'string', ['null' => false, 'limit' => 255])
      ->addColumn('added', 'datetime', ['null' => false])
      ->addColumn('nickname', 'string', ['null' => false, 'limit' => 25])
      ->addColumn('confirm', 'integer', ['null' => false, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10])
      ->addColumn('confirm_string', 'string', ['null' => false, 'limit' => 10])
      ->addColumn('about', 'text', ['null' => false, 'limit' => 65535])
      ->addColumn('contactway', 'string', ['null' => false, 'limit' => 255])
      ->addColumn('payway', 'string', ['null' => false, 'limit' => 255])
      ->addColumn('skills', 'string', ['null' => false, 'limit' => 255])
      ->addColumn('timezone', 'string', ['null' => false, 'limit' => 10])
      ->addColumn('w9_status', 'enum', ['null' => true, 'default' => 'not-applicable', 'limit' => 16, 'values' => ['awaiting-receipt','pending-approval','approved','rejected','not-applicable']])
      ->addColumn('w9_accepted', 'datetime', ['null' => true])
      ->addColumn('first_name', 'string', ['null' => true, 'limit' => 30])
      ->addColumn('last_name', 'string', ['null' => true, 'limit' => 30])
      ->addColumn('is_runner', 'boolean', ['null' => false, 'default' => '0', 'limit' => MysqlAdapter::INT_TINY, 'precision' => 3])
      ->addColumn('is_payer', 'boolean', ['null' => false, 'default' => '0', 'limit' => MysqlAdapter::INT_TINY, 'precision' => 3])
      ->addColumn('journal_nick', 'string', ['null' => true, 'limit' => 60])
      ->addColumn('is_guest', 'integer', ['null' => true, 'default' => '0', 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10])
      ->addColumn('int_code', 'string', ['null' => false, 'limit' => 5])
      ->addColumn('is_active', 'boolean', ['null' => false, 'default' => '1', 'limit' => MysqlAdapter::INT_TINY, 'precision' => 3])
      ->addColumn('last_seen', 'datetime', ['null' => true])
      ->addColumn('github_connected', 'boolean', ['null' => true, 'limit' => MysqlAdapter::INT_TINY, 'precision' => 3])
      ->addColumn('github_token', 'string', ['null' => true, 'limit' => 40])
      ->addColumn('github_commit', 'string', ['null' => true, 'limit' => 250])
      ->addColumn('phone', 'string', ['null' => true, 'limit' => 16])
      ->addColumn('smsaddr', 'string', ['null' => true, 'limit' => 255])
      ->addColumn('country', 'string', ['null' => true, 'limit' => 2])
      ->addColumn('provider', 'string', ['null' => true, 'default' => 'NULL', 'limit' => 64])
      ->addColumn('has_sandbox', 'boolean', ['null' => false, 'default' => '0', 'limit' => MysqlAdapter::INT_TINY, 'precision' => 3])
      ->addColumn('unixusername', 'string', ['null' => true, 'limit' => 30])
      ->addColumn('forgot_hash', 'string', ['null' => false, 'limit' => 32])
      ->addColumn('forgot_expire', 'datetime', ['null' => false])
      ->addColumn('paypal', 'boolean', ['null' => false, 'limit' => MysqlAdapter::INT_TINY, 'precision' => 3])
      ->addColumn('paypal_verified', 'integer', ['null' => true, 'limit' => MysqlAdapter::INT_TINY, 'precision' => 3, 'signed' => false])
      ->addColumn('paypal_email', 'string', ['null' => true, 'limit' => 255])
      ->addColumn('paypal_hash', 'string', ['null' => true, 'limit' => 255])
      ->addColumn('budget', 'decimal', ['null' => false, 'precision' => 10, 'scale' => 2])
      ->addColumn('openid', 'string', ['null' => true, 'limit' => 255])
      ->addColumn('sms_flags', 'integer', ['null' => false, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'signed' => false])
      ->addColumn('filter', 'text', ['null' => true, 'limit' => 65535])
      ->addColumn('findus', 'string', ['null' => false, 'default' => 'NA', 'limit' => 255])
      ->addColumn('is_giver', 'integer', ['null' => false, 'default' => '1', 'limit' => MysqlAdapter::INT_TINY, 'precision' => 3])
      ->addColumn('is_receiver', 'integer', ['null' => false, 'default' => '1', 'limit' => MysqlAdapter::INT_TINY, 'precision' => 3])
      ->addColumn('old_id', 'integer', ['null' => false, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10])
      ->addColumn('is_admin', 'integer', ['null' => false, 'default' => '0', 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10])
      ->addColumn('annual_salary', 'decimal', ['null' => false, 'precision' => 10, 'scale' => 2])
      ->addColumn('picture', 'string', ['null' => true, 'limit' => 256])
      ->addColumn('bidding_emails', 'integer', ['null' => false, 'default' => '0', 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10])
      ->addColumn('notifications', 'integer', ['null' => false, 'default' => '0', 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10])
      ->addColumn('manager', 'integer', ['null' => false, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10])
      ->addColumn('city', 'string', ['null' => true, 'default' => '', 'limit' => 50])
      ->addColumn('has_W2', 'integer', ['null' => false, 'default' => '0', 'limit' => MysqlAdapter::INT_TINY, 'precision' => 3, 'signed' => false])
      ->addColumn('referred_by', 'integer', ['null' => false, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10])
      ->addColumn('s3bucket', 'string', ['null' => true, 'limit' => 64])
      ->addColumn('phone_confirm_string', 'string', ['null' => true, 'limit' => 4])
      ->addColumn('phone_verified', 'datetime', ['null' => true])
      ->addColumn('phone_rejected', 'datetime', ['null' => true])
      ->addColumn('sound_settings', 'integer', ['null' => false, 'default' => '31', 'limit' => MysqlAdapter::INT_TINY, 'precision' => 3])
      ->addColumn('bidding_notif', 'integer', ['null' => false, 'default' => '0', 'limit' => MysqlAdapter::INT_TINY, 'precision' => 3])
      ->addColumn('review_notif', 'integer', ['null' => false, 'default' => '0', 'limit' => MysqlAdapter::INT_TINY, 'precision' => 3])
      ->addColumn('self_notif', 'integer', ['null' => false, 'default' => '0', 'limit' => MysqlAdapter::INT_TINY, 'precision' => 3])
      ->addColumn('is_internal', 'boolean', ['null' => true, 'default' => '0', 'limit' => MysqlAdapter::INT_TINY, 'precision' => 3])
      ->addIndex(['username'], ['name' => "username", 'unique' => true])
      ->addIndex(['nickname'], ['name' => "nickname", 'unique' => true])
      ->addIndex(['id'], ['name' => "id", 'unique' => false])
      ->addIndex(['manager'], ['name' => "manager", 'unique' => false])
      ->addIndex(['referred_by'], ['name' => "referred_by", 'unique' => false])
      ->addIndex(['nickname'], ['name' => "nickname_2", 'unique' => false, 'type' => 'fulltext'])
      ->save();
  }

  public function down() {
    $this->dropTable('users');
  }
}
