var skills = [
'.NET',
'Access DB',
'Active Directory',
'AJAX',
'Amazon Kindle',
'Android',
'Apache',
'ASP',
'Asterisk PBX',
'Azure',
'Balsamiq',
'Blackberry',
'BMC Remedy',
'Boonex Dolphin',
'C#',
'C/C++',
'CakePHP',
'Chordiant',
'Chrome OS',
'Cisco',
'Cloud Computing/EC2',
'CMS',
'COBOL',
'Cocoa',
'Codeigniter',
'Cold Fusion',
'Computer Security',
'CUDA',
'Delphi',
'Django',
'DNS',
'DotNetNuke',
'Drupal',
'eCommerce',
'Electronic Forms',
'Embedded Software',
'Erlang',
'Expression Engine',
'Facebook',
'Forum Software',
'Game Design',
'Google Analytics',
'Google App Engine',
'Google Go',
'Google Wave',
'GPGPU',
'HP Openview',
'IIS',
'iPad',
'iPhone',
'iSeries / AS400',
'J2EE',
'J2ME',
'Java',
'JavaFX',
'Javascript',
'Joomla',
'JSP',
'Link Building',
'Linux',
'MacOS',
'Magento',
'Metatrader',
'Microsoft',
'MMORPG',
'MODx',
'MS Exchange',
'MS Expression',
'MySpace',
'MySQL',
'Nginx',
'Nokia',
'NoSQL Couch/Mongo',
'Objective C',
'Oracle',
'OSCommerce',
'Palm',
'Paypal API',
'Perl',
'PHP',
'Prestashop',
'Prolog',
'Protoshare',
'PSD Coding',
'Python',
'REALbasic',
'Ruby/Ruby on Rails',
'SAP',
'Script Installation',
'Second Life / Virtual Worlds',
'SEO',
'Sharepoint',
'Shell Script',
'Shopping Carts',
'Silverlight',
'Social Networking',
'SocialEngine',
'Software Architecture',
'Software Testing',
'SQL',
'Symbian',
'System Admin.',
'Twitter',
'UML Design',
'User Interface / IA',
'vBulletin',
'Visual Basic',
'VoIP',
'Volusion',
'vTiger',
'Web Scraping',
'Website QA',
'Website Security',
'WinCE',
'Windows',
'Windows Mobile',
'Wordpress',
'XML',
'YouTube',
'Zen Cart',
'Zend',


'Academic Writing',
'Article Rewriting',
'Articles',
'Astroturfing',
'Blog',
'Cartography/Maps',
'Copywriting',
'eBooks',
'Editing',
'Fiction',
'Finance Research',
'Forum Posting',
'Ghostwriting',
'Grant Writing',
'LaTeX',
'Medical Writing',
'PDF',
'Powerpoint',
'Product Descriptions',
'Proofreading',
'Publishing',
'Report Writing',
'Research',
'Reviews',
'Technical Writing',
'Translation',
'Travel Writing',


'After Effects',
'Animation',
'Art & Craft',
'Audio Services',
'Banner Design',
'Building Architecture',
'Business Cards',
'Caricature / Cartoons',
'Conceptual Design',
'Corporate Identity',
'CSS',
'Dreamweaver',
'Fashion Design',
'Flash',
'Flex',
'Graphic Design',
'Illustration',
'Illustrator',
'InDesign',
'Industrial Design',
'Interior Design',
'Layout / Formatting',
'Logo Design',
'Maya',
'Music',
'Packaging / Covers',
'Photo Editing',
'Photography',
'Photoshop',
'Print',
'PSD Design',
'PSD to HTML',
'PSD2CMS',
'QuarkXPress',
'Rendering/3D',
'Stationery Design',
'Templates',
'Transcription',
'Typography',
'Video Broadcasting',
'Video Services',
'Voice Talent',
'Website Design',
'Word',


'BPO',
'Customer Support',
'Data Entry',
'Data Processing',
'Desktop Support',
'Excel',
'Order Processing',
'Phone Support',
'Technical Support',
'Video Uploading',
'Virtual Assistant',
'Web Search',


'Algorithmic',
'AutoCAD',
'Biology',
'Biotechnology',
'CAD/CAM',
'Chemical Engineering',
'Civil Engineering',
'Construction Monitoring',
'Cryptography',
'Electrical Engineering',
'Electronics',
'Engineering',
'Finite Element Analysis',
'Geology',
'Handheld / PDA',
'Home Design Drafting',
'Machine Learning',
'Manufacturing Design',
'Materials Engineering',
'Matlab/Mathematica',
'Mechanical Engineering',
'Mechatronics',
'Medical',
'Microcontroller',
'Natural Language',
'PCB Layout',
'PLC / SCADA',
'Project Scheduling',
'Quantum',
'Scientific Research',
'Solidworks',
'Statistical Analysis',
'Structural Engineering',
'Verilog / VHDL',
'Wireless',


'Buyer Sourcing',
'Logistics & Shipping',
'Manufacturing',
'Product Sourcing',
'Supplier Sourcing',


'Advertising',
'Branding',
'Bulk Marketing',
'Craigslist',
'CRM',
'eBay',
'eMarketing',
'Google Adsense',
'Leads',
'Marketing',
'MLM',
'Sales',
'SEM / Adwords',
'Telemarketing',


'Accounting',
'Business Analysis',
'Business Plans',
'Contracts',
'ERP',
'Event Planning',
'Finance',
'Human Resources',
'Inventory Management',
'Legal',
'Legal Research',
'Management',
'Patents',
'Payroll',
'PeopleSoft',
'Project Management',
'Public Relations',
'Quickbooks/Quicken/MYOB',
'Recruiting',
'Tax',
'Automotive',
'Dating',
'Financial Markets',
'Genealogy',
'Health',
'Insurance',
'Sports',
'Test Automation',
'Testing / QA',
'Training',
'Troubleshooting',
'Tutoring / Education',
'Weddings',
'XXX'
];
 
