    <!-- Popup to penalize user -->
    <div id="popup-penalty" class="popup-body" title = "Penalize user">
      <form id="penalty" method="post">
	<p class = "info-label">You are about to penalize <span id = "nicknamed" style = "font-weight: bold; color: red;"></span><br />
	</p>
	<p class = "info-label">Reason:<br />
	  <textarea name="penalty-reason" size = "48" class = "probo"></textarea><br />
	</p>
	<input type="submit" name="penalize-cancel" value="Cancel" />
	<input type="submit" name="penalize" value="Penalize" />
      </form>
    </div><!-- End of popup for penalize user --> 