    <!-- Popup to penalize user -->
    <div id="popup-guest-selector" class="popup-body" title = "Send Guest to Penalty Box">
	<h3>Please select guest user you want to penalize:</h3>
	<div id = "guest-list">
	    <div class = "guest-entry">
I'm a nasty guest!
	    </div>
	    <div class = "guest-entry">
I'm not so great either!
	    </div>
	    <div class = "guest-entry">
I talk too much!
	    </div>
	    <div class = "guest-entry">
I talk too much!
	    </div>
	    <div class = "guest-entry">
I talk too much!
	    </div>
	</div>
    </div><!-- End of popup for penalize user --> 
