    <div id="popup-bid-info" class="popup-body" title = "Bid Info">
            <form name = "popup-form" id = "popup-form" action="" method="post">
            <input type="hidden" name="bid_id" value="" />
            <p class = "info-label">Email<br />
            <span id="info-email"></span>
            </p>

            <p class = "info-label">Bid Amount<br />
            <span id="info-bid-amount"></span>
            </p>

            <p class = "info-label">Done By<br />
            <span id="info-bid-done-by"></span>
            </p>

            <p class = "info-label">Notes<br />
            <span id="info-notes"></span>
            </p>

            </form>
    </div>
