<div id="popup-pingtask" title = "Ping about task" class = "popup-body">
	<form name="popup-form" id="popup-form-edit" action="" method="post">
		<input type="hidden" name="itemid" value="0" />

		<h5>Ping about the task progress.</h5>
		<input type="text" id="ping-msg" name="ping-msg"></input>
		<input type="checkbox" id="send-mail" name="send_mail" checked="true">Also send email.</input>
		<input type="submit" id="send-ping-btn" value="Send ping" style="float:right;"></input>
		
	</form>
</div>
