Welcome to the Worklist development team!  Ready to get started?

Your sandbox account details:
Server: dev.worklist.net
username: {USERNAME}
password: {PASSWORD}

This account can be used for accessing the server using SFTP or SSH.

-- If you review someone's code at their request, or help someone with a Worklist item, you can add a fee to that item in the Worklist. Just click on that item in the Worklist, click the "View" button, click "Add Fee", and enter an amount and description of the work you have done.  Again, you can determine the best amount to charge by looking at other items in the Worklist.

-- To begin working on one of our Worklist items, go to http://svn.worklist.net/ to find the appropriate SubVersion repository.  Click on the one you want, and you will see the command to enter in SSH to check it out.  Run the command from your public_html directory to check out a copy of the source code.  You will then be able to work with the code there, and test your changes in a browser by going to dev.worklist.net/~{USERNAME}/<repositoryname>.  Be sure to update Subversion frequently to stay current on other changes.

-- Once you have completed your changes, ask for us to check your code by using the Live Workroom chat or by email.  Once the code has been checked, you can commit your changes to Subversion.  For Subversion help, type "svn ?" in SSH.

-- Information on payment and other details can be found at http://www.lovemachineinc.com/development-process/.  For any other questions, ask in the Live Workroom chat or by email.  We value transparency and open discussion, so don't hesitate to ask questions or make suggestions.  Have fun!

See you in the Workroom!

