<?php
/**
 * Sms number/provider list
 *
 * @package Sms
 * @version $Id$
 */
/**
 * Sms number/provider list
 *
 * @package Sms
 */
class Sms_Numberlist
{
    public static $codeList = array(
        "Afghanistan" => "93",
        "Albania" => "355",
        "Algeria" => "213",
        "Andorra" => "376",
        "Angola" => "244",
        "Anguilla" => "1264",
        "Antigua & Barbuda" => "1268",
        "Argentina" => "54",
        "Armenia" => "374",
        "Aruba" => "297",
        "Australia" => "61",
        "Austria" => "43",
        "Azerbaijan" => "994",
        "Bahamas, the" => "1242",
        "Bahrain" => "973",
        "Bangladesh" => "880",
        "Barbados" => "1246",
        "Barbuda" => "1268",
        "Belarus" => "375",
        "Belgium" => "32",
        "Belize" => "501",
        "Benin" => "229",
        "Bermuda" => "1441",
        "Bhutan" => "975",
        "Bolivia" => "591",
        "Bosnia-Herzegovina" => "387",
        "Botswana" => "267",
        "Brazil" => "55",
        "British Virgin Islands" => "1284",
        "Brunei" => "673",
        "Bulgaria" => "359",
        "Burkina Faso" => "226",
        "Burundi" => "257",
        "Cambodia" => "855",
        "Cameroon" => "237",
        "Canada" => "1",
        "Canary Islands" => "34",
        "Cape Verde" => "238",
        "Cayman Islands" => "1345",
        "Central African Republic" => "236",
        "Chad" => "235",
        "Chile" => "56",
        "China" => "86",
        "Colombia" => "57",
        "Comoros" => "269",
        "Congo" => "242",
        "Congo, Democratic Republic" => "243",
        "Cook Islands" => "682",
        "Costa Rica" => "506",
        "Croatia" => "385",
        "Cuba" => "53",
        "Curacao" => "5999",
        "Cyprus" => "357",
        "Czech Republic" => "420",
        "Denmark" => "45",
        "Djibouti" => "253",
        "Dominica" => "1767",
        "Dominican Republic" => "1",
        "East Timor" => "670",
        "Ecuador" => "593",
        "Egypt" => "20",
        "El Salvador" => "503",
        "Equatorial Guinea" => "240",
        "Estonia" => "372",
        "Ethiopia" => "251",
        "Falkland Islands" => "500",
        "Faroe Islands" => "298",
        "Fiji" => "679",
        "Finland" => "358",
        "France" => "33",
        "French Guiana" => "594",
        "French Polynesia" => "689",
        "French West Indies" => "590",
        "Gabon" => "241",
        "Gambia" => "220",
        "Georgia" => "995",
        "Germany" => "49",
        "Ghana" => "233",
        "Gibraltar" => "350",
        "Greece" => "30",
        "Greenland" => "299",
        "Grenada" => "1473",
        "Guadeloupe" => "590",
        "Guam" => "1671",
        "Guatemala" => "502",
        "Guernsey" => "44",
        "Guinea" => "224",
        "Guyana" => "592",
        "Haiti" => "509",
        "Honduras" => "504",
        "HongKong" => "852",
        "Hungary" => "36",
        "Iceland" => "354",
        "India" => "91",
        "Indonesia" => "62",
        "Iran" => "98",
        "Iraq" => "964",
        "Ireland" => "353",
        "Isle of Man" => "44",
        "Israel" => "972",
        "Italy" => "39",
        "Ivory Coast" => "225",
        "Jamaica" => "1876",
        "Japan" => "81",
        "Jersey" => "44",
        "Jordan" => "962",
        "Kazakhstan" => "7",
        "Kenya" => "254",
        "Korea (South)" => "82",
        "Kuwait" => "965",
        "Kyrgyzstan" => "996",
        "Lao" => "856",
        "Latvia" => "371",
        "Lebanon" => "961",
        "Lesotho" => "266",
        "Liberia" => "231",
        "Libya" => "218",
        "Liechtenstein" => "423",
        "Lithuania" => "370",
        "Luxembourg" => "352",
        "Macau" => "853",
        "Macedonia" => "389",
        "Madagascar" => "261",
        "Malawi" => "265",
        "Malaysia" => "60",
        "Maldives" => "960",
        "Mali" => "223",
        "Malta" => "356",
        "Martinique" => "596",
        "Mauritania" => "222",
        "Mauritius" => "230",
        "Mayotte Island (Comoros)" => "269",
        "Mexico" => "52",
        "Moldova" => "373",
        "Monaco (Kosovo)" => "377",
        "Mongolia" => "976",
        "Montenegro" => "382",
        "Montserrat" => "1664",
        "Morocco" => "212",
        "Mozambique" => "258",
        "Myanmar" => "95",
        "Namibia" => "264",
        "Nauru" => "674",
        "Nepal" => "977",
        "Netherlands" => "31",
        "Netherlands Antilles" => "599",
        "New Caledonia" => "687",
        "New Zealand" => "64",
        "Nicaragua" => "505",
        "Niger" => "227",
        "Nigeria" => "234",
        "Norway" => "47",
        "Oman" => "968",
        "Pakistan" => "92",
        "Palestine (+970)" => "970",
        "Palestine (+9725)" => "9725",
        "Panama" => "507",
        "Papua New Guinea" => "675",
        "Paraguay" => "595",
        "Peru" => "51",
        "Philippines" => "63",
        "Poland" => "48",
        "Portugal" => "351",
        "Puerto Rico" => "1",
        "Qatar" => "974",
        "Reunion" => "262",
        "Romania" => "40",
        "Russia" => "7",
        "Rwanda" => "250",
        "Saipan" => "1670",
        "Samoa (American)" => "1684",
        "Samoa (Western)" => "685",
        "San Marino" => "378",
        "Saudi Arabia" => "966",
        "Senegal" => "221",
        "Serbia" => "381",
        "Seychelles" => "248",
        "Sierra Leone" => "232",
        "Singapore" => "65",
        "Slovakia" => "421",
        "Slovenia" => "386",
        "Solomon Islands" => "677",
        "Somalia" => "252",
        "South Africa" => "27",
        "Spain" => "34",
        "Sri Lanka" => "94",
        "St. Kitts And Nevis" => "1869",
        "St. Lucia" => "1758",
        "St. Vincent" => "1784",
        "Sudan" => "249",
        "Suriname" => "597",
        "Swaziland" => "268",
        "Sweden" => "46",
        "Switzerland" => "41",
        "Syria" => "963",
        "Taiwan" => "886",
        "Tajikistan" => "992",
        "Tanzania" => "255",
        "Thailand" => "66",
        "Togo" => "228",
        "Tonga Islands" => "676",
        "Trinidad and Tobago" => "1868",
        "Tunisia" => "216",
        "Turkey" => "90",
        "Turkmenistan" => "993",
        "Turks and Caicos Islands" => "1649",
        "Uganda" => "256",
        "UK" => "44",
        "Ukraine" => "380",
        "United Arab Emirates" => "971",
        "Uruguay" => "598",
        "US Virgin Islands" => "1340",
        "USA" => "1",
        "Uzbekistan" => "998",
        "Vanuatu" => "678",
        "Vatican City State" => "39",
        "Venezuela" => "58",
        "Vietnam" => "84",
        "Yemen" => "967",
        "Zambia" => "260",
        "Zanzibar" => "259",
        "Zimbabwe" => "263"
        );

        public static $providerList = array(
    'US'=>array(    /* United States */
        '3 River Wireless'=>'{n}@sms.3rivers.net',
        '7-11 Speakout'=>'{n}@cingularme.com',
        'Advantage Communications'=>'{n}@advantagepaging.com',
        'Airtouch Pagers'=>'{n}@airtouch.net',
        'Airtouch Pagers'=>'{n}@airtouch.net',
        'Airtouch Pagers'=>'{n}@airtouchpaging.com',
        'Airtouch Pagers'=>'{n}@alphapage.airtouch.com',
        'Airtouch Pagers'=>'{n}@myairmail.com',
        'AllTel'=>'{n}@message.alltel.com',
        'Alltel PCS'=>'{n}@message.alltel.com',
        'Alltel'=>'{n}@alltelmessage.com',
        'AirVoice'=>'{n}@mmode.com',
        'Ameritech'=>'{n}@pagin.acswireless.com',
        'Aql'=>'{n}@text.aql.com',
        'Arch Pagers (PageNet)'=>'{n}@archwireless.net',
        'Arch Pagers (PageNet)'=>'{n}@epage.arch.com',
        'AT&T Wireless'=>'{n}@txt.att.net',
        'Bell South'=>'{n}@blsdcs.net',
        'Bell South Blackberry'=>'{n}@bellsouthtips.com',
        'Bell South Mobility'=>'{n}@blsdcs.net',
        'Bell South SMS'=>'{n}@sms.bellsouth.com',
        'Bell South Wireless'=>'{n}@wireless.bellsouth.com',
        'Bluegrass Cellular'=>'{n}@sms.bluecell.com',
        'Boost Mobile'=>'{n}@myboostmobile.com',
        'Boost'=>'{n}@myboostmobile.com',
        'CallPlus'=>'{n}@mmode.com',
        'Carolina Mobile Communications'=>'{n}@cmcpaging.com',
        'Cellular One'=>'{n}@message.cellone-sf.com',
        'Cellular One East Coast'=>'{n}@phone.cellone.net',
        'Cellular One Mobile'=>'{n}@mobile.celloneusa.com',
        'Cellular One PCS'=>'{n}@paging.cellone-sf.com',
        'Cellular One SBC'=>'{n}@sbcemail.com',
        'Cellular One South West'=>'{n}@swmsg.com',
        'Cellular One West'=>'{n}@mycellone.com',
        'Cellular South'=>'{n}@csouth1.com',
        'Central Vermont Communications'=>'{n}@cvcpaging.com',
        'CenturyTel'=>'{n}@messaging.centurytel.net',
        'Cingular (GSM)'=>'{n}@cingularme.com',
        'Cingular (TDMA)'=>'{n}@mmode.com',
        'Cingular Wireless'=>'{n}@mobile.mycingular.net',
        'Cingular'=>'{n}@cingularme.com',
        'Communication Specialists'=>'{n}@pageme.comspeco.net',
        'Cook Paging'=>'{n}@cookmail.com',
        'Corr Wireless Communications'=>'{n}@corrwireless.net',
        'Cricket'=>'{n}@sms.mycricket.com',
        'Dobson Communications Corporation'=>'{n}@mobile.dobson.net',
        'Dobson-Alex Wireless / Dobson-Cellular One'=>'{n}@mobile.cellularone.com',
        'Edge Wireless'=>'{n}@sms.edgewireless.com',
        'Galaxy Corporation'=>'{n}@sendabeep.net',
        'GCS Paging'=>'{n}@webpager.us',
        'Globalstart'=>'{n}@msg.globalstarusa.com',
        'GTE'=>'{n}@gte.pagegate.net',
        'GTE'=>'{n}@messagealert.com',
        'GrayLink / Porta-Phone'=>'{n}@epage.porta-phone.com',
        'Houston Cellular'=>'{n}@text.houstoncellular.net',
        'Illinois Valley Cellular'=>'{n}@ivctext.com',
        'Inland Cellular Telephone'=>'{n}@inlandlink.com',
        'Iridium'=>'{n}@msg.iridium.com',
        'JSM Tele-Page'=>'{n}@jsmtel.com',
        'Lauttamus Communication'=>'{n}@e-page.net',
        'MCI Phone'=>'{n}@mci.com',
        'MCI'=>'{n}@pagemci.com',
        'Metro PCS'=>'{n}@mymetropcs.com',
        'Metrocall'=>'{n}@page.metrocall.com',
        'Metrocall 2-way'=>'{n}@my2way.com',
        'Midwest Wireless'=>'{n}@clearlydigital.com',
        'Mobilecom PA'=>'{n}@page.mobilcom.net',
        'Mobilfone'=>'{n}@page.mobilfone.com',
        'MobiPCS'=>'{n}@mobipcs.net',
        'Morris Wireless'=>'{n}@beepone.net',
        'Nextel'=>'{n}@messaging.nextel.com',
        'NPI Wireless'=>'{n}@npiwireless.com',
        'Ntelos'=>'{n}@pcs.ntelos.com',
        'O2'=>'{n}@mobile.celloneusa.com',
        'Omnipoint'=>'{n}@omnipoint.com',
        'Omnipoint'=>'{n}@omnipointpcs.com',
        'OnlineBeep'=>'{n}@onlinebeep.net',
        'Orange'=>'{n}@mobile.celloneusa.com',
        'PCS One'=>'{n}@pcsone.net',
        'Pacific Bell'=>'{n}@pacbellpcs.net',
        'PageMart'=>'{n}@pagemart.net',
        'PageOne NorthWest'=>'{n}@page1nw.com',
        'Pioneer / Enid Cellular'=>'{n}@msg.pioneerenidcellular.com',
        'Price Communications'=>'{n}@mobilecell1se.com',
        'ProPage'=>'{n}@page.propage.net',
        'Public Service Cellular'=>'{n}@sms.pscel.com',
        'Qualcomm'=>'name@pager.qualcomm.com',
        'Qwest'=>'{n}@qwestmp.com',
        'RAM Page'=>'{n}@ram-page.com',
        'Rogers Wireless'=>'{n}@pcs.rogers.com',
        'Safaricom'=>'{n}@safaricomsms.com',
        'Satelindo GSM'=>'{n}@satelindogsm.com',
        'Satellink'=>'{n}.pageme@satellink.net',
        'Simple Freedom'=>'{n}@text.simplefreedom.net',
        'Skytel Pagers'=>'{n}@email.skytel.com',
        'Skytel Pagers'=>'{n}@skytel.com',
        'Smart Telecom'=>'{n}@mysmart.mymobile.ph',
        'Southern LINC'=>'{n}@page.southernlinc.com',
        'Southwestern Bell'=>'{n}@email.swbw.com',
        'Sprint PCS'=>'{n}@messaging.sprintpcs.com',
        'ST Paging'=>'pin@page.stpaging.com',
        'SunCom'=>'{n}@tms.suncom.com',
        'Surewest Communications'=>'{n}@mobile.surewest.com',
        'T-Mobile'=>'{n}@tmomail.net',
        'Teleflip'=>'{n}@teleflip.com',
        'Teletouch'=>'{n}@pageme.teletouch.com',
        'Telus'=>'{n}@msg.telus.com',
        'The Indiana Paging Co'=>'{n}@pager.tdspager.com',
        'Tracfone'=>'{n}@mmst5.tracfone.com',
        'Triton'=>'{n}@tms.suncom.com',
        'TIM'=>'{n}@timnet.com',
        'TSR Wireless'=>'{n}@alphame.com',
        'TSR Wireless'=>'{n}@beep.com',
        'US Cellular'=>'{n}@email.uscc.net',
        'USA Mobility'=>'{n}@mobilecomm.net',
        'Unicel'=>'{n}@utext.com',
        'Verizon'=>'{n}@vtext.com',
        'Verizon PCS'=>'{n}@myvzw.com',
        'Verizon Pagers'=>'{n}@myairmail.com',
        'Virgin Mobile'=>'{n}@vmobl.com',
        'Virgin Mobile'=>'{n}@vxtras.com',
        'WebLink Wireless'=>'{n}@pagemart.net',
        'West Central Wireless'=>'{n}@sms.wcc.net',
        'Western Wireless'=>'{n}@cellularonewest.com',
        'Wyndtell'=>'{n}@wyndtell.com',
        ),
    'AR'=>array(    /* Argentina */
        'CTI'=>'{n}@sms.ctimovil.com.ar',
        'Movicom'=>'{n}@sms.movistar.net.ar',
        'Nextel'=>'TwoWay.11{n}@nextel.net.ar',
        'Personal'=>'{n}@alertas.personal.com.ar',
        ),
    'AW'=>array(    /* Aruba */
        'Setar Mobile'=>'297+{n}@mas.aw',
        ),
    'AU'=>array(    /* Australia */
        'Blue Sky Frog'=>'{n}@blueskyfrog.com',
        'Optus Mobile'=>'0{n}@optusmobile.com.au',
        'SL Interactive'=>'{n}@slinteractive.com.au',
        ),
    'AT'=>array(    /* Austria */
        'MaxMobil'=>'{n}x@max.mail.at',
        'One Connect'=>'{n}@onemail.at',
        'Provider'=>'E-mail to SMS address format',
        'T-Mobile'=>'43676{n}@sms.t-mobile.at',
        ),
    'BE'=>array(    /* Belgium */
        'Mobistar'=>'{n}@mobistar.be',
        ),
    'BM'=>array(    /* Bermuda */
        'Mobility'=>'{n}@ml.bm',
        ),
    'BR'=>array(    /* Brazil */
        'Claro'=>'{n}@clarotorpedo.com.br',
        'Nextel'=>'{n}@nextel.com.br',
        ),
    'BG'=>array(    /* Bulgaria */
        'Globul'=>'{n}@sms.globul.bg',
        'Mtel'=>'{n}@sms.mtel.net',
        ),
    'CA'=>array(    /* Canada */
        'Aliant'=>'{n}@wirefree.informe.ca',
        'Bell Mobility'=>'{n}@txt.bellmobility.ca',
        'Fido'=>'{n}@fido.ca',
        'Koodo Mobile'=>'{n}@msg.koodomobile.com',
        'Microcell'=>'{n}@fido.ca',
        'MTS Mobility'=>'{n}@text.mtsmobility.com',
        'NBTel'=>'{n}@wirefree.informe.ca',
        'PageMart'=>'{n}@pmcl.net',
        'PageNet'=>'{n}@pagegate.pagenet.ca',
        'Presidents Choice'=>'{n}@mobiletxt.ca',
        'Rogers Wireless'=>'{n}@pcs.rogers.com',
        'Sasktel Mobility'=>'{n}@pcs.sasktelmobility.com',
        'Telus'=>'{n}@msg.telus.com',
        'Virgin Mobile'=>'{n}@vmobile.ca',
        ),
    'CL'=>array(    /* Chile */
        'Bell South'=>'{n}@bellsouth.cl',
        ),
    'CO'=>array(    /* Columbia */
        'Comcel'=>'{n}@comcel.com.co',
        'Moviastar'=>'{n}@movistar.com.co',
        ),
    'CZ'=>array(    /* Czech Republic */
        'Eurotel'=>'+ccaa@sms.eurotel.cz',
        'Oskar'=>'{n}@mujoskar.cz',
        ),
    'DK'=>array(    /* Denmark */
        'Sonofon'=>'{n}@note.sonofon.dk',
        'Tele Danmark Mobil'=>'{n}@sms.tdk.dk',
        'Telia Denmark'=>'{n}@gsm1800.telia.dk',
        ),
    'EE'=>array(    /* Estonia */
        'EMT'=>'{n}@sms.emt.ee',
        ),
    'FR'=>array(    /* France */
        'SFR'=>'{n}@sfr.fr',
        ),
    'DE'=>array(    /* Germany */
        'E-Plus'=>'0{n}.sms@eplus.de',
        'Mannesmann Mobilefunk'=>'0{n}@d2-message.de',
        'O2'=>'0{n}@o2online.de',
        'T-Mobile'=>'{n}@t-mobile-sms.de',
        'Vodafone'=>'0{n}@vodafone-sms.de',
        ),
    'HU'=>array(    /* Hungary */
        'PGSM'=>'3620{n}@sms.pgsm.hu',
        ),
    'IS'=>array(    /* Iceland */
        'OgVodafone'=>'{n}@sms.is',
        'Siminn'=>'{n}@box.is',
        ),
    'IN'=>array(    /* India */
        'Andhra Pradesh AirTel'=>'91{n}@airtelap.com',
        'Andhra Pradesh Idea Cellular'=>'9848{n}@ideacellular.net',
        'BPL mobile'=>'{n}@bplmobile.com',
        'Chennai Skycell / Airtel'=>'919840{n}@airtelchennai.com',
        'Chennai RPG Cellular'=>'9841{n}@rpgmail.net',
        'Delhi Airtel'=>'919810{n}@airtelmail.com',
        'Delhi Hutch'=>'9811{n}@delhi.hutch.co.in',
        'Gujarat Idea Cellular'=>'9824{n}@ideacellular.net',
        'Gujarat Airtel'=>'919898{n}@airtelmail.com',
        'Gujarat Celforce / Fascel'=>'9825{n}@celforce.com',
        'Goa Airtel'=>'919890{n}@airtelmail.com',
        'Goa BPL Mobile'=>'9823{n}@bplmobile.com',
        'Goa Idea Cellular'=>'9822{n}@ideacellular.net',
        'Haryana Airtel'=>'919896{n}@airtelmail.com',
        'Haryana Escotel'=>'9812{n}@escotelmobile.com',
        'Himachal Pradesh Airtel'=>'919816{n}@airtelmail.com',
        'Idea Cellular'=>'{n}@ideacellular.net',
        'Karnataka Airtel'=>'919845{n}@airtelkk.com',
        'Kerala Airtel'=>'919895{n}@airtelkerala.com',
        'Kerala Escotel'=>'9847{n}@escotelmobile.com',
        'Kerala BPL Mobile'=>'9846{n}@bplmobile.com',
        'Kolkata Airtel'=>'919831{n}@airtelkol.com',
        'Madhya Pradesh Airtel'=>'919893{n}@airtelmail.com',
        'Maharashtra Airtel'=>'919890{n}@airtelmail.com',
        'Maharashtra BPL Mobile'=>'9823{n}@bplmobile.com',
        'Maharashtra Idea Cellular'=>'9822{n}@ideacellular.net',
        'Mumbai Airtel'=>'919892{n}@airtelmail.com',
        'Mumbai BPL Mobile'=>'9821{n}@bplmobile.com',
        'Orange'=>'{n}@orangemail.co.in',
        'Punjab Airtel'=>'919815{n}@airtelmail.com',
        'Pondicherry BPL Mobile'=>'9843{n}@bplmobile.com',
        'Tamil Nadu Airtel'=>'919894{n}@airtelmail.com',
        'Tamil Nadu BPL Mobile'=>'919843{n}@bplmobile.com',
        'Tamil Nadu Aircel'=>'9842{n}@airsms.com',
        'Uttar Pradesh West Escotel'=>'9837{n}@escotelmobile.com',
        ),
    'IE'=>array(    /* Ireland */
        'Meteor'=>'{n}@sms.mymeteor.ie',
        'Meteor MMS'=>'{n}@mms.mymeteor.ie',
        ),
    'IT'=>array(    /* Italy */
        'Telecom Italia Mobile'=>'33{n}@posta.tim.it',
        'Vodafone'=>'{n}@sms.vodafone.it',
        'Vodafone Omnitel'=>'34{n}@vizzavi.it',
        ),
    'JP'=>array(    /* Japan */
        'AU by KDDI'=>'{n}@ezweb.ne.jp',
        'NTT DoCoMo'=>'{n}@docomo.ne.jp',
        'Vodafone Chuugoku/Western'=>'{n}@n.vodafone.ne.jp',
        'Vodafone Hokkaido'=>'{n}@d.vodafone.ne.jp',
        'Vodafone Hokuriko/Central North'=>'{n}@r.vodafone.ne.jp',
        'Vodafone Kansai/West, including Osaka'=>'{n}@k.vodafone.ne.jp',
        'Vodafone Kanto/Koushin/East, including Tokyo'=>'{n}@t.vodafone.ne.jp',
        'Vodafone Kyuushu/Okinawa'=>'{n}@q.vodafone.ne.jp',
        'Vodafone Shikoku'=>'{n}@s.vodafone.ne.jp',
        'Vodafone Touhoku/Niigata/North'=>'{n}@h.vodafone.ne.jp',
        'Vodafone Toukai/Central'=>'{n}@c.vodafone.ne.jp',
        'Willcom'=>'{n}@pdx.ne.jp',
        'Willcom di'=>'{n}@di.pdx.ne.jp',
        'Willcom dj'=>'{n}@dj.pdx.ne.jp',
        'Willcom dk'=>'{n}@dk.pdx.ne.jp',
        ),
    'LV'=>array(    /* Latvia */
        'Kyivstar'=>'{n}@smsmail.lmt.lv',
        'LMT'=>'9{n}@smsmail.lmt.lv',
        'Tele2'=>'{n}@sms.tele2.lv',
        ),
    'LB'=>array(    /* Lebanon */
        'Cellis / LibanCell'=>'9613{n}@ens.jinny.com.lb',
        ),
    'LU'=>array(    /* Luxembourg */
        'P&amp;T Luxembourg'=>'{n}@sms.luxgsm.lu',
        ),
    'MY'=>array(    /* Malaysia */
        'Celcom'=>'019{n}@sms.celcom.com.my',
        ),
    'MU'=>array(    /* Mauritius */
        'Emtel'=>'{n}@emtelworld.net',
        ),
    'MX'=>array(    /* Mexico */
        'Iusacell'=>'{n}@rek2.com.mx',
        ),
    'NI'=>array(    /* Nicaragua */
        'Claro'=>'{n}@ideasclaro-ca.com',
        ),
    'NP'=>array(    /* Nepal */
        'Mero Mobile'=>'{n}@sms.spicenepal.com',
        ),
    'NL'=>array(    /* Netherlands */
        'Dutchtone / Orange-NL'=>'{n}@sms.orange.nl',
        'T-Mobile'=>'31{n}@gin.nl',
        ),
    'NO'=>array(    /* Norway */
        'Netcom'=>'{n}@sms.netcom.no',
        'Telenor'=>'{n}@mobilpost.no',
        ),
    'PA'=>array(    /* Panama */
        'Cable and Wireless'=>'{n}@cwmovil.com',
        ),
    'PL'=>array(    /* Poland */
        'Orange Polska'=>'{n}@orange.pl',
        'Plus GSM'=>'+4860{n}@text.plusgsm.pl',
        ),
    'PT'=>array(    /* Portugal */
        'Telcel'=>'91{n}@sms.telecel.pt',
        'Optimus'=>'93{n}@sms.optimus.pt',
        'TMN'=>'96{n}@mail.tmn.pt',
        ),
    'RU'=>array(    /* Russia */
        'BeeLine GSM'=>'{n}@sms.beemail.ru',
        'MTS'=>'7{n}x@sms.mts.ru',
        'Personal Communication'=>'sms@pcom.ru (number in subject line)',
        'Primtel'=>'{n}@sms.primtel.ru',
        'SCS-900'=>'{n}@scs-900.ru',
        'Uraltel'=>'{n}@sms.uraltel.ru',
        'Vessotel'=>'{n}@pager.irkutsk.ru',
        'YCC'=>'{n}@sms.ycc.ru',
        ),
    'CS'=>array(    /* Serbia and Montenegro */
        'Mobtel Srbija'=>'{n}@mobtel.co.yu',
        ),
    'SG'=>array(    /* Singapore */
        'M1'=>'{n}@m1.com.sg',
        ),
    'SI'=>array(    /* Slovenia */
        'Mobitel'=>'{n}@linux.mobitel.si',
        'Si Mobil'=>'{n}@simobil.net',
        ),
    'ZA'=>array(    /* South Africa */
        'MTN'=>'{n}@sms.co.za',
        'Vodacom'=>'{n}@voda.co.za',
        ),
    'ES'=>array(    /* Spain */
        'Telefonica Movistar'=>'{n}@movistar.net',
        'Vodafone'=>'{n}@vodafone.es',
        ),
    'LK'=>array(    /* Sri Lanka */
        'Mobitel'=>'{n}@sms.mobitel.lk',
        ),
    'SE'=>array(    /* Sweden */
        'Comviq GSM'=>'467{n}@sms.comviq.se',
        'Europolitan'=>'4670{n}@europolitan.se',
        'Tele2'=>'0{n}@sms.tele2.se',
        ),
    'CH'=>array(    /* Switzerland */
        'Sunrise Mobile'=>'{n}@freesurf.ch',
        'Sunrise Mobile'=>'{n}@mysunrise.ch',
        'Swisscom'=>'{n}@bluewin.ch',
        ),
    'TZ'=>array(    /* Tanzania */
        'Mobitel'=>'{n}@sms.co.tz',
        ),
    'UA'=>array(    /* Ukraine */
        'Golden Telecom'=>'{n}@sms.goldentele.com',
        'Kyivstar'=>'{n}x@2sms.kyivstar.net',
        'UMC'=>'{n}@sms.umc.com.ua',
        ),
    'GB'=>array(    /* United Kingdom */
        'BigRedGiant Mobile'=>'{n}@tachyonsms.co.uk',
        'O2'=>'44{n}@mobile.celloneusa.com',
        'O2 (M-mail)'=>'44{n}@mmail.co.uk',
        'Orange'=>'0{n}@orange.net',
        'T-Mobile'=>'0{n}@t-mobile.uk.net',
        'Virgin Mobile'=>'0{n}@vxtras.com',
        'Vodafone'=>'0{n}@vodafone.net',
        ),
        );

}