<div id="contact-dialog">
    <form id="contact-form" action="" method="post" onsubmit="return false;">
        <p><strong>Name:</strong><br /><input class="text-field" type="text" name="name" id="name" value="" /></p>
        <p><strong>Email:</strong><br /><input class="text-field" type="text" name="email" id="email" value="" /></p>
        <p><strong>Phone#:</strong><br /><input class="text-field" type="text" name="phone" id="phone" value="" /></p>
        <p><strong>Project Name:</strong><br /><input class="text-field" type="text" name="project" id="project" value="" /></p>
        <p><strong>Project Description:</strong><br /><textarea name="proj-desc" id="proj-desc"></textarea></p>
        <p><input type="submit" id="contact-submit" value="Send Message" /> &nbsp; <input type="button" id="contact-close" value="Cancel" /></p>
    </form>
</div>
