<div id="contact-dialog">
    <form id="contact-form" action="" method="post" onsubmit="return false;">
        <p><strong>Name:</strong><br /><input class="text-field" type="text" name="name" id="contactName" value="" /></p>
        <p><strong>Email:</strong><br /><input class="text-field" type="text" name="email" id="contactEmail" value="" /></p>
        <p><strong>Phone#:</strong><br /><input class="text-field" type="text" name="phone" id="contactPhone" value="" /></p>
        <p><strong>Project Name:</strong><br /><input class="text-field" type="text" name="project" id="contactProject" value="" /></p>
        <p><strong>Project Website:</strong><br /><input class="text-field" type="text" name="website" id="contactWebsite" value="" /></p>
        <p><strong>Project Description:</strong><br /><textarea name="proj-desc" id="contactProjDesc"></textarea></p>
        <p><input type="submit" class="disableable" id="contact-submit" value="Send Message" /> &nbsp; <input type="button" id="contact-close" value="Cancel" /></p>
    </form>
</div>
