<div id="popup-pingtask" title="Ping about task" class="popup-body">
    <form name="popup-form" id="popup-form-edit" action="" method="post">
        <input type="hidden" name="itemid" value="0" />
        <textarea id="ping-msg" name="ping-msg" rows="3"></textarea>
        <input type="checkbox" id="send-mail" name="send_mail" checked="checked" class="hidden" />
        <input type="submit" id="send-ping-btn" value="Send ping" class="floatRight" />
        <p><input type="checkbox" id="echo-journal" name="echo_journal" checked="checked" /> Echo to public journal</p>
        <p><input type="checkbox" id="copy-me" name="copy_me" checked="checked" /> Copy me in email</p>
        <div class="clear"></div>
    </form>
</div>