<div id="add-runner" class="popup-body" title="Add Runner">
    <form action="" method="post" id="addRunner-form">
        <div class="clear">
            <p>Enter a username to be added as a Runner for this project.</p>
        </div>
        <div class="floatLeft">
            <span class="project-label" id="addRunner-label">Add Runner</span>
            <input type="text" class="add-runner ac_input" name="addrunner" id="addrunner-textbox" autocomplete="on" />
        </div>
        <div class="buttonContainer">
            <input type="submit" name="add-runner" value="Add" />
        </div>
    </form>
</div>