    <div id="popup-decline-bid" class="popup-body" title = "Decline Bid">
            <form name = "popup-form" id = "popup-form" action="" method="post">
		    <input type="hidden" name="bid_id" value="" />   
                <p class="info-label">Why is this bid being declined?<br />
                <textarea name="decline_bid_reason" size="48" /></textarea>
                </p>
                <br/><input type="submit" id="decline_bid" name="decline_bid" value="Decline Bid" />
            </form>
    </div>
