<div id="w9-dialog" style="display:none">  
    <p><strong>First Name:</strong><br /><input class="text-field" type="text" name="first_name" id="first_name" value="" /></p>
    <p><strong>Last Name:</strong><br /><input class="text-field" type="text" name="last_name" id="last_name" value="" /></p>
    <p><input id="formupload" type="button" value="upload W9" style="float:left;margin-left: 8px;" ></input></p>
    <br style="clear:both" />
    <div class="uploadnotice-w9"></div>
    <br style="clear:both" />         
</div>
