<div id="popup-pingtask" title="Ping about task" class="popup-body">
    <form name="popup-form" id="popup-form-edit" action="" method="post">
        <input type="hidden" name="itemid" value="0" />
        <input type="hidden" name="bidder" value="0" />
        <textarea id="ping-msg" name="ping-msg" rows="3"></textarea>
        <input type="checkbox" id="send-mail" name="send_mail" checked="checked" class="hidden" />
        <p>
            <span id="echo-journal-span">
                <label id="echo-journal_label" for="echo-journal" class="checkbox-label">
                    <input type="checkbox" id="echo-journal" name="echo_journal" checked="checked" /> 
                    Echo to public chat
                </label>
            </span>
            <label for="copy-me" class="checkbox-label">
                <input type="checkbox" id="copy-me" name="copy_me" checked="checked" />
                Copy me in email
            </label>
        </p>
        <input type="submit" id="send-ping-btn" value="Send ping" class="floatRight" />
        <div class="clear"></div>
    </form>
</div>