<div id="popup-pp-extended-info" class="popup-body" title = "Transaction Information">
    <div style="float:left;margin-left:35px;">
	    <p><b>ID</b></p>
	    <span id="id"></span>
	    <br/>
	    <p><b>Fee ID</b></p>
	    <span id="fee-id"></span>
	    <br/>
    </div>
    <div style="float:left;margin-left:35px;">
        <p><b>PayPal email</b></p>
        <span id="pp-email"></span>
        <br/>
	    <p><b>Amount</b></p>
	    <span id="amount"></span>
	    <br/>
	    <p><b>Payment Fee</b></p>
	    <span id="pay-fee"></span>
	    <br/>
	    <p><b>Currency</b></p>
	    <span id="currency"></span>
	    <br/>
    </div>
    <div style="float:left;margin-left:35px;">
	    <p><b>Mass Pay Run ID</b></p>
	    <span id="mass-pay-desc"></span>
	    <br/>
        <div id="mass-pay-run-stats-div" style="display:none;">
            <p><b>Mass Pay Run Status</b></p>
	        <span id="mass-pay-run-stats"></span>
	        <br/>
        </div>
	    <div id="mass-pay-run-reason-div" style="display:none;">
	       <p><b>Mass Pay Status Reason</b></p>
	        <span id="mass-pay-run-reason"></span>
	        <br/>
        </div>
    </div>
    <div style="float:left;margin-left:35px;margin-right:35px;">
        <p><b>Date of Payment</b></p>
        <span id="date"></span>
        <br/>
	    <p><b>Payment Status</b></p>
	    <span id="status"></span>
	    <br/>
	    <div id="deny-reason-div" style="display:none;">
		    <p><b>Deny Reason</b></p>
		    <span id="deny-reason"></span>
		    <br/>
	    </div>
    </div>
</div><!-- end of popup-bid -->
