<div id="popup-pingtask" title="Ping about task" class="popup-body">
    <form name="popup-form" id="popup-form-edit" action="" method="post">
        <input type="hidden" name="itemid" value="0" />
        <textarea id="ping-msg" name="ping-msg" rows="3" style="height: 65px;"></textarea>
        <input type="checkbox" id="send-mail" name="send_mail" checked="checked" style="display: none;" />
        <input type="checkbox" id="echo-journal" name="echo_journal" checked="checked" /> Echo to public journal
        <input type="submit" id="send-ping-btn" value="Send ping" style="float:right;" />
        <div style="clear: both;"></div>
    </form>
</div>