<div id="add-codereviewer" class="popup-body" title="Add Code Reviewer">
    <form action="" method="post" id="addcodereviewer-form">
        <div class="clear">
            <p>Enter a username to be added as a Code Reviewer for this project.</p>
        </div>
        <div class="floatLeft">
            <span class="project-label" id="addcodereviewer-label">Add Code Reviewer</span>
            <input type="text" class="add-codeReviewer" name="addcodereviewer" id="addcodereviewer-textbox" />
            <input type="submit" id="add-reviewer-submit" name="add-codereviewer" value="Add" />
        </div>
    </form>
</div>