    <div id="popup-fee-info" class="popup-body" title="Fee Info">
        <table border="0">
            <tr>
                <td>User</td>
                <td><span id="info-fee-email"></span></td>
            </tr>
            <tr>
                <td>Amount</td>
                <td>$<span id="info-fee-amount"></span></td>
            </tr>
            <tr>
                <td>Fee Entered</td>
                <td><span id="info-fee-created"></span></td>
            </tr>
            <tr>
                <td>Notes</td>
                <td class="textJustify"><div id="info-fee-notes"></div></td>
            </tr>
        </table>
        <div class="clear"></div>
        <br/>
    </div>
