<div id="w9-dialog" style="display:none">
    <div>
        <strong>First Name:</strong>
        <br />
        <input class="text-field" type="text" name="first_name" id="first_name" value="" />
    </div>
    <div>
        <strong>Last Name:</strong>
        <br />
        <input class="text-field" type="text" name="last_name" id="last_name" value="" />
    </div>
    <div>
        <input id="formupload" type="button" value="upload W9" />
        <div class="w9_loader"></div>
    </div>
    <div class="uploadnotice-w9"></div>

    <div id="sent-notify" style="display: none;"></div>
</div>
