<div id="popup-addproject" class="popup-body" title = "Add Project">
            We are currently taking applications from interested companies or individuals
            who would like to run their own projects on the Worklist. If you are interested,
            send us an email to <b>contact at lovemachineinc</b>. Tell us about your project, and
            the amount of total budget you would like to allocate to doing development here.
            We'll get in touch quickly!
			<br />
			 
    </div>
    
    