        <div id = "jobs-popup" style = "display: none;" title = "Jobs list">
            <table>
                <thead>
                    <tr class = "table-hdng">
                        <th>Job #</th><th>Summary</th><th>Creator</th><th>Runner</th><th>Date</th>
                    </tr>
                </thead>
                <tbody><tr><td></td></tr>
                </tbody>
            </table>
        </div>

        <div id = "latest-earnings-popup" style = "display: none;" title = "Fees for the last 30 days">
            <table>
                <thead>
                    <tr class = "table-hdng">
                        <th>Job #</th><th>Fee amount</th><th>Summary</th><th>Creator</th><th>Runner</th><th>Paid</th>
                    </tr>
                </thead>
                <tbody><tr><td></td></tr>
                </tbody>
            </table>
        </div>

        <div id = "lovelist-popup" style = "display: none;"  title = "Love received">
            <table>
                <thead>
                    <tr class = "table-hdng">
                        <th>From</th><th>Why</th><th>When</th>
                    </tr>
                </thead>
                <tbody><tr><td></td></tr>
                </tbody>
            </table>
        </div> 
