<div id="remove-runner" class="popup-body" title ="Remove Runners">
    <form action="" method="post" id="removeRunner-form">
        <table width="100%" id="project-runners">
            <thead>
    	        <tr class="table-hdng">
    	            <td class="remove-runner-nickname" >Nickname</td>
    	            <td class="remove-runner-label" >Remove</td>
    	        </tr>
    	    </thead>
    	    <tbody>
    	    </tbody>
    	</table>
    <div class="buttonContainer">
        <input type="submit" name="remove-runner" value="Ok" />
    </div>
    </form>
</div>