    <div id="popup-ineligible" class="popup-body" title="Your account is ineligible">
        <strong>You are not eligible</strong> to bid or place fees on this item. Please check your settings and make sure you have:
        <ul>
            <li>Verified your Paypal address</li>
            <li>Uploaded your completed <a href="http://www.irs.gov/pub/irs-pdf/fw9.pdf">W-9</a> (US citizens only)</li>
        </ul>
        <br/>
        <input type="button" id="button_settings" name="button_settings" value="Edit settings" />
    </div>
