<div id="popup-reviewurl" title="Functional &amp; Review URL" class="popup-body" style="padding-right:5px;">
    <form name="popup-form" id="popup-form-reviewurl" action="" method="post">
        <div style="float:left;width:90%">
        <p>Please add any specific notes if needed for the Runner and/or code reviewer, and be sure your sandbox is current.</p>
        <p class="info-label">Sandbox URL to Review<br />
        <input type="text" name="sandbox-url" id="sandbox-url" class="text-field"/><br />
        Notes<br />
        <input type="text" name="review-notes" id="review-notes" title="Add notes for Runner &amp; Code Reviewer if needed." class="text-field"/>
        <input type="hidden" name="quick-status-review" id="quick-status-review"/>
        </p>
        </div>
        <input type="submit" name="save-review-url" value="Save" id="save-review-url" style="position:relative; left:264px;" />
     </form>
</div>

