<div id="popup-reviewurl" title="Review URL" class="popup-body" style="padding-right:5px;">
	<form name="popup-form" id="popup-form-reviewurl" action="" method="post">
		<div style="float:left;width:90%">
     	<p class="info-label">Sandbox URL to Review<br />
      		<input type="text" name="sandbox-url" id="sandbox-url" class="text-field"  />
      	</p>
    	</div>
    	<input type="submit" name="save-review-url" value="Save" id="save-review-url" style="position:relative; left:264px;" />
 	</form>
</div>

